"""add coach profile fields

Revision ID: 0478ab5f57c1
Revises: 88bd3f6971d6
Create Date: 2026-06-24 10:06:38.812907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0478ab5f57c1'
down_revision: Union[str, Sequence[str], None] = '88bd3f6971d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entrenadores', sa.Column('nombre', sa.String(), nullable=True))
    op.add_column('entrenadores', sa.Column('anios_experiencia', sa.Integer(), nullable=True))
    op.alter_column('rutinas', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rutinas', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rutinas', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('rutinas', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('entrenadores', 'anios_experiencia')
    op.drop_column('entrenadores', 'nombre')
    # ### end Alembic commands ###
