"""add_coach_finances_and_phone

Revision ID: 334d85db9cef
Revises: 542a66294e22
Create Date: 2026-08-06 17:49:45.454658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334d85db9cef'
down_revision: Union[str, Sequence[str], None] = '542a66294e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entrenadores', sa.Column('tipo_cobro_alumnos', sa.String(), nullable=True))
    op.add_column('entrenadores', sa.Column('precio_cobro_alumnos', sa.Float(), nullable=True))
    op.add_column('usuarios', sa.Column('telefono', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'telefono')
    op.drop_column('entrenadores', 'precio_cobro_alumnos')
    op.drop_column('entrenadores', 'tipo_cobro_alumnos')
    # ### end Alembic commands ###
