"""add fecha_nacimiento

Revision ID: 35531aea3ccd
Revises: ad3284f59d41
Create Date: 2026-10-09 13:48:49.641725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35531aea3ccd'
down_revision: Union[str, Sequence[str], None] = 'ad3284f59d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumnos', sa.Column('fecha_nacimiento', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alumnos', 'fecha_nacimiento')
    # ### end Alembic commands ###
