"""init_schema

Revision ID: 4efb7ebd8f31
Revises: 
Create Date: 2026-05-16 20:17:09.024344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4efb7ebd8f31'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('entrenadores',
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('especialidad', sa.String(), nullable=True),
    sa.Column('biografia', sa.String(), nullable=True),
    sa.Column('url_foto_perfil', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('alumnos',
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('id_entrenador', sa.UUID(), nullable=False),
    sa.Column('peso_corporal_actual', sa.Float(), nullable=True),
    sa.Column('objetivo', sa.String(), nullable=True),
    sa.Column('estado_activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_entrenador'], ['entrenadores.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('ejercicios',
    sa.Column('id_ejercicio', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('url_media', sa.String(), nullable=True),
    sa.Column('id_entrenador', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_entrenador'], ['entrenadores.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_ejercicio')
    )
    op.create_table('rutinas',
    sa.Column('id_rutina', sa.UUID(), nullable=False),
    sa.Column('id_entrenador', sa.UUID(), nullable=False),
    sa.Column('nombre_rutina', sa.String(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_entrenador'], ['entrenadores.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_rutina')
    )
    op.create_table('entrenamiento_sesiones',
    sa.Column('id_sesion', sa.UUID(), nullable=False),
    sa.Column('id_alumno', sa.UUID(), nullable=False),
    sa.Column('id_rutina', sa.UUID(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_alumno'], ['alumnos.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_rutina'], ['rutinas.id_rutina'], ),
    sa.PrimaryKeyConstraint('id_sesion')
    )
    op.create_table('rutinas_dias',
    sa.Column('id_dia', sa.UUID(), nullable=False),
    sa.Column('id_rutina', sa.UUID(), nullable=False),
    sa.Column('nombre_dia', sa.String(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_rutina'], ['rutinas.id_rutina'], ),
    sa.PrimaryKeyConstraint('id_dia')
    )
    op.create_table('rutinas_ejercicios',
    sa.Column('id_rutina_ejercicio', sa.UUID(), nullable=False),
    sa.Column('id_dia', sa.UUID(), nullable=False),
    sa.Column('id_ejercicio', sa.UUID(), nullable=False),
    sa.Column('series_esperadas', sa.Integer(), nullable=False),
    sa.Column('reps_esperadas', sa.Integer(), nullable=False),
    sa.Column('descanso_segundos', sa.Integer(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_dia'], ['rutinas_dias.id_dia'], ),
    sa.ForeignKeyConstraint(['id_ejercicio'], ['ejercicios.id_ejercicio'], ),
    sa.PrimaryKeyConstraint('id_rutina_ejercicio')
    )
    op.create_table('entrenamiento_sets_reales',
    sa.Column('id_set', sa.UUID(), nullable=False),
    sa.Column('id_sesion', sa.UUID(), nullable=False),
    sa.Column('id_rutina_ejercicio', sa.UUID(), nullable=False),
    sa.Column('peso_usado', sa.Float(), nullable=False),
    sa.Column('reps_logradas', sa.Integer(), nullable=False),
    sa.Column('rpe', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_rutina_ejercicio'], ['rutinas_ejercicios.id_rutina_ejercicio'], ),
    sa.ForeignKeyConstraint(['id_sesion'], ['entrenamiento_sesiones.id_sesion'], ),
    sa.PrimaryKeyConstraint('id_set')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entrenamiento_sets_reales')
    op.drop_table('rutinas_ejercicios')
    op.drop_table('rutinas_dias')
    op.drop_table('entrenamiento_sesiones')
    op.drop_table('rutinas')
    op.drop_table('ejercicios')
    op.drop_table('alumnos')
    op.drop_table('entrenadores')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
