"""add_superadmin_finances

Revision ID: 542a66294e22
Revises: d3bd51611ea2
Create Date: 2026-08-06 17:13:10.983350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '542a66294e22'
down_revision: Union[str, Sequence[str], None] = 'd3bd51611ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagos_entrenadores',
    sa.Column('id_pago', sa.UUID(), nullable=False),
    sa.Column('id_entrenador', sa.UUID(), nullable=False),
    sa.Column('anio_mes', sa.String(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('metodo_pago', sa.String(), nullable=True),
    sa.Column('notas', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_entrenador'], ['entrenadores.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_pago')
    )
    op.create_index(op.f('ix_pagos_entrenadores_anio_mes'), 'pagos_entrenadores', ['anio_mes'], unique=False)
    op.add_column('entrenadores', sa.Column('estado_activo', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('entrenadores', sa.Column('modelo_pago', sa.String(), server_default=sa.text("'por_alumno'"), nullable=False))
    op.add_column('entrenadores', sa.Column('monto_fijo', sa.Float(), nullable=True))
    op.create_index(op.f('ix_entrenadores_estado_activo'), 'entrenadores', ['estado_activo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entrenadores_estado_activo'), table_name='entrenadores')
    op.drop_column('entrenadores', 'monto_fijo')
    op.drop_column('entrenadores', 'modelo_pago')
    op.drop_column('entrenadores', 'estado_activo')
    op.drop_index(op.f('ix_pagos_entrenadores_anio_mes'), table_name='pagos_entrenadores')
    op.drop_table('pagos_entrenadores')
    # ### end Alembic commands ###
