"""Add id_rutina_activa to Alumno

Revision ID: 88bd3f6971d6
Revises: a929e3e3280e
Create Date: 2026-06-09 20:02:20.828106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88bd3f6971d6'
down_revision: Union[str, Sequence[str], None] = 'a929e3e3280e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumnos', sa.Column('id_rutina_activa', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'alumnos', 'rutinas', ['id_rutina_activa'], ['id_rutina'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alumnos', type_='foreignkey')
    op.drop_column('alumnos', 'id_rutina_activa')
    # ### end Alembic commands ###
