"""add_invitacion_table

Revision ID: a929e3e3280e
Revises: 4efb7ebd8f31
Create Date: 2026-05-21 20:52:23.768517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a929e3e3280e'
down_revision: Union[str, Sequence[str], None] = '4efb7ebd8f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitaciones',
    sa.Column('id_invitacion', sa.UUID(), nullable=False),
    sa.Column('id_entrenador', sa.UUID(), nullable=False),
    sa.Column('codigo_unico', sa.String(), nullable=False),
    sa.Column('email_destinatario', sa.String(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_expiracion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_entrenador'], ['entrenadores.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_invitacion')
    )
    op.create_index(op.f('ix_invitaciones_codigo_unico'), 'invitaciones', ['codigo_unico'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitaciones_codigo_unico'), table_name='invitaciones')
    op.drop_table('invitaciones')
    # ### end Alembic commands ###
