"""fase_a_suscripciones

Revision ID: ace047de4a78
Revises: 0478ab5f57c1
Create Date: 2026-06-24 17:06:48.411029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace047de4a78'
down_revision: Union[str, Sequence[str], None] = '0478ab5f57c1'
branch_labels: Union[str, Sequence[str], None] = None
"""fase_a_suscripciones

Revision ID: ace047de4a78
Revises: 0478ab5f57c1
Create Date: 2026-06-24 17:06:48.411029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace047de4a78'
down_revision: Union[str, Sequence[str], None] = '0478ab5f57c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alumnos_estado_activo'), 'alumnos', ['estado_activo'], unique=False)
    op.add_column('entrenadores', sa.Column('limite_alumnos', sa.Integer(), server_default='10', nullable=False))
    op.add_column('entrenadores', sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True))
    op.add_column('entrenadores', sa.Column('estado_financiero', sa.String(), server_default='activo', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entrenadores', 'estado_financiero')
    op.drop_column('entrenadores', 'fecha_vencimiento')
    op.drop_column('entrenadores', 'limite_alumnos')
    op.drop_index(op.f('ix_alumnos_estado_activo'), table_name='alumnos')
    # ### end Alembic commands ###
