"""Add performance indexes to foreign keys

Revision ID: ad3284f59d41
Revises: a1b2c3d4e5f6
Create Date: 2026-10-01 20:06:11.374075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad3284f59d41'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alumnos', 'clases_usadas_total',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_alumnos_id_entrenador'), 'alumnos', ['id_entrenador'], unique=False)
    op.create_index(op.f('ix_alumnos_id_rutina_activa'), 'alumnos', ['id_rutina_activa'], unique=False)
    op.drop_index(op.f('ix_asistencias_qr_alumno'), table_name='asistencias_qr')
    op.drop_index(op.f('ix_asistencias_qr_entrenador'), table_name='asistencias_qr')
    op.create_index(op.f('ix_asistencias_qr_id_alumno'), 'asistencias_qr', ['id_alumno'], unique=False)
    op.create_index(op.f('ix_asistencias_qr_id_entrenador'), 'asistencias_qr', ['id_entrenador'], unique=False)
    op.create_index(op.f('ix_ejercicios_id_entrenador'), 'ejercicios', ['id_entrenador'], unique=False)
    op.alter_column('entrenadores', 'tipo_cuenta',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'estandar'::character varying"))
    op.create_index(op.f('ix_entrenamiento_sesiones_id_alumno'), 'entrenamiento_sesiones', ['id_alumno'], unique=False)
    op.create_index(op.f('ix_entrenamiento_sesiones_id_rutina'), 'entrenamiento_sesiones', ['id_rutina'], unique=False)
    op.create_index(op.f('ix_entrenamiento_sets_reales_id_rutina_ejercicio'), 'entrenamiento_sets_reales', ['id_rutina_ejercicio'], unique=False)
    op.create_index(op.f('ix_entrenamiento_sets_reales_id_sesion'), 'entrenamiento_sets_reales', ['id_sesion'], unique=False)
    op.create_index(op.f('ix_rutinas_id_entrenador'), 'rutinas', ['id_entrenador'], unique=False)
    op.create_index(op.f('ix_rutinas_dias_id_rutina'), 'rutinas_dias', ['id_rutina'], unique=False)
    op.create_index(op.f('ix_rutinas_ejercicios_id_dia'), 'rutinas_ejercicios', ['id_dia'], unique=False)
    op.create_index(op.f('ix_rutinas_ejercicios_id_ejercicio'), 'rutinas_ejercicios', ['id_ejercicio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rutinas_ejercicios_id_ejercicio'), table_name='rutinas_ejercicios')
    op.drop_index(op.f('ix_rutinas_ejercicios_id_dia'), table_name='rutinas_ejercicios')
    op.drop_index(op.f('ix_rutinas_dias_id_rutina'), table_name='rutinas_dias')
    op.drop_index(op.f('ix_rutinas_id_entrenador'), table_name='rutinas')
    op.drop_index(op.f('ix_entrenamiento_sets_reales_id_sesion'), table_name='entrenamiento_sets_reales')
    op.drop_index(op.f('ix_entrenamiento_sets_reales_id_rutina_ejercicio'), table_name='entrenamiento_sets_reales')
    op.drop_index(op.f('ix_entrenamiento_sesiones_id_rutina'), table_name='entrenamiento_sesiones')
    op.drop_index(op.f('ix_entrenamiento_sesiones_id_alumno'), table_name='entrenamiento_sesiones')
    op.alter_column('entrenadores', 'tipo_cuenta',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'estandar'::character varying"))
    op.drop_index(op.f('ix_ejercicios_id_entrenador'), table_name='ejercicios')
    op.drop_index(op.f('ix_asistencias_qr_id_entrenador'), table_name='asistencias_qr')
    op.drop_index(op.f('ix_asistencias_qr_id_alumno'), table_name='asistencias_qr')
    op.create_index(op.f('ix_asistencias_qr_entrenador'), 'asistencias_qr', ['id_entrenador'], unique=False)
    op.create_index(op.f('ix_asistencias_qr_alumno'), 'asistencias_qr', ['id_alumno'], unique=False)
    op.drop_index(op.f('ix_alumnos_id_rutina_activa'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_id_entrenador'), table_name='alumnos')
    op.alter_column('alumnos', 'clases_usadas_total',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
