"""add_fecha_ultimo_peso

Revision ID: b13323ffee87
Revises: ace047de4a78
Create Date: 2026-06-25 15:51:23.246383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b13323ffee87'
down_revision: Union[str, Sequence[str], None] = 'ace047de4a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamificacion_umbrales',
    sa.Column('id_umbral', sa.UUID(), nullable=False),
    sa.Column('ejercicio_nombre', sa.String(), nullable=False),
    sa.Column('nivel_nombre', sa.String(), nullable=False),
    sa.Column('subnivel', sa.Integer(), nullable=False),
    sa.Column('multiplicador_requerido', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id_umbral')
    )
    op.create_table('ejercicios_media_coaches',
    sa.Column('id_override', sa.UUID(), nullable=False),
    sa.Column('id_ejercicio', sa.UUID(), nullable=False),
    sa.Column('id_entrenador', sa.UUID(), nullable=False),
    sa.Column('url_media', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_ejercicio'], ['ejercicios.id_ejercicio'], ),
    sa.ForeignKeyConstraint(['id_entrenador'], ['entrenadores.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_override')
    )
    op.create_table('historial_ejercicios_alumnos',
    sa.Column('id_historial', sa.UUID(), nullable=False),
    sa.Column('id_alumno', sa.UUID(), nullable=False),
    sa.Column('id_ejercicio', sa.UUID(), nullable=False),
    sa.Column('last_e1rm', sa.Float(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_alumno'], ['alumnos.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_ejercicio'], ['ejercicios.id_ejercicio'], ),
    sa.PrimaryKeyConstraint('id_historial')
    )
    op.create_table('log_ligas_alumnos',
    sa.Column('id_log', sa.UUID(), nullable=False),
    sa.Column('id_alumno', sa.UUID(), nullable=False),
    sa.Column('ejercicio_nombre', sa.String(), nullable=False),
    sa.Column('nivel_alcanzado', sa.String(), nullable=False),
    sa.Column('subnivel_alcanzado', sa.Integer(), nullable=False),
    sa.Column('fecha_logro', sa.DateTime(), nullable=True),
    sa.Column('estado_validacion', sa.String(), nullable=False),
    sa.Column('e1rm_logrado', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_alumno'], ['alumnos.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.add_column('alumnos', sa.Column('fecha_ultimo_peso', sa.DateTime(), nullable=True))
    op.add_column('rutinas', sa.Column('frecuencia_semanal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rutinas', 'frecuencia_semanal')
    op.drop_column('alumnos', 'fecha_ultimo_peso')
    op.drop_table('log_ligas_alumnos')
    op.drop_table('historial_ejercicios_alumnos')
    op.drop_table('ejercicios_media_coaches')
    op.drop_table('gamificacion_umbrales')
    # ### end Alembic commands ###
