"""Add PagoAlumno table

Revision ID: d3bd51611ea2
Revises: ab894c24f413
Create Date: 2026-06-27 12:01:18.890575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3bd51611ea2'
down_revision: Union[str, Sequence[str], None] = 'ab894c24f413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagos_alumnos',
    sa.Column('id_pago', sa.UUID(), nullable=False),
    sa.Column('id_alumno', sa.UUID(), nullable=False),
    sa.Column('id_entrenador', sa.UUID(), nullable=False),
    sa.Column('anio_mes', sa.String(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('metodo_pago', sa.String(), nullable=True),
    sa.Column('notas', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_alumno'], ['alumnos.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_entrenador'], ['entrenadores.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_pago')
    )
    op.create_index(op.f('ix_pagos_alumnos_anio_mes'), 'pagos_alumnos', ['anio_mes'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_alumnos_anio_mes'), table_name='pagos_alumnos')
    op.drop_table('pagos_alumnos')
    # ### end Alembic commands ###
